name: Deploy to Algorithmia

on:
  push:
    branches:
      - master
      - prod_algorithmia

jobs:
  algorithmia-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2.0.0
        with:
          ref: ${{github.sha}}
      - name: Deploy Model to Algorithmia
        uses: aslisabanci/algorithmia_ci_modeldeployment@master
        env:
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
        with:
          algorithmia_api_key: ${{ secrets.ALGORITHMIA_API_KEY }}
          algorithmia_username: ${{ secrets.ALGORITHMIA_USERNAME }}
          algorithmia_email: ${{ secrets.ALGORITHMIA_EMAIL }}
          algorithmia_password: ${{ secrets.ALGORITHMIA_PASSWORD }}
          algorithmia_algoname:  demo_jameskenny
          # notebook_path: notebook_with.ipynb
          # model_path: model_with_specific_name.pkl
          # algorithmia_uploadpath: data://${{ env.ALGORITHMIA_USERNAME }}/${{ env.ALGORITHMIA_ALGONAME }}
      - name: Publish on Algorithmia
        if: github.ref == 'refs/heads/prod_algorithmia'
        run: echo "I am triggered on prod_algorithmia branch"
        # uses: PUBLISH ACTION REF here - TO BE IMPLEMENTED
        # with:
        #   algorithmia_api_key: ...
        #   version_schema: minor? major?
        #   algorithm_tests_dir: ?
        
